### ISSUE TITLE
MSIE/Edge Support

### ISSUE THREAD

**Issue by lochstar** [Wildhoney/Interpose#1]
This is a great idea. Since CSS variables are being used, not all browsers are supported. Have you had any thoughts about adding support for older browsers?

**Comment by Wildhoney** [comment]
Thanks @lochstar!

As with a good portion of my GitHub modules, they are experimental, and looking toward the future of web development. I know [CSSNext](http://cssnext.io/) supports basic CSS Variables with the `:root` selector, but apart from that we're out of luck until browsers implement CSS Variables natively.

It's terribly difficult to have a workaround, as they're dynamic variables &mdash; very much unlike SASS variables. CSSNext provides a basic interface for updating the variables dynamically, but I'm not sure whether Interpose should concern itself with that, due to the limited support of selectors (just `:root`) and its necessary diversion from the actual CSS Variable spec.

Thoughts?
